USE [master]
GO
CREATE LOGIN [etl] WITH PASSWORD =N'etlpass', DEFAULT_DATABASE = [AdventureWorksDW2022], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE AdventureWorksDW2022
GO
CREATE USER [etl] FOR LOGIN [etl]
GO
USE AdventureWorksDW2022
GO
ALTER ROLE [db_datareader] ADD MEMBER [etl]
GO
use [master]
GO
GRANT CONNECT SQL TO [etl]
GO